# -*- coding: utf-8 -*-
"""activida de clase y tutoria adiccional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_QWgFF6fAg-9LkF0reRwZxJUD6AjH1Y4

# **REPASO DE CLASE**
"""



#CARGA DE MODULOS
import pandas as pd
import numpy as np

df=pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2024/2024-10-22/cia_factbook.csv")

df.info()

df.head(5)

df.tail(10)

peso = pd.Series([67,68,70])

peso

talla = pd.Series([1.70,"1.60m",1.80])

talla

df.describe()

df['country']

filtro = df['country'] =="Colombia"

filtro

df[filtro]

df[df['country'] =="Colombia"]

df[(df['country'] =="Colombia") |(df["country"] =="Russia")]



df[df['death_rate'] <=7.9]

df_low_m=df[df['death_rate'] <=7.9]

df_low_m.describe()

df[(df['death_rate'] <=8)&(df['life_exp_at_birth'] >=60)]

df2=df[(df['death_rate'] <=8)&(df['life_exp_at_birth'] >=60)]

df2.head()

df2.describe()

df.describe()

df[(df['life_exp_at_birth']>=60)&(df['life_exp_at_birth']<=90)]

df3=df[(df['life_exp_at_birth']>=60)&(df['life_exp_at_birth']<=90)]

df3.describe()

df[df['life_exp_at_birth'].between(60,90)]