# -*- coding: utf-8 -*-
"""actividad.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgYI8jEYQzfwHpW4f71At3t7BvRvU0Ic

##clase introduccion datos de netflix

instalacion de pandas
"""

!pip install pandas

"""###que es pandas y para que sirve

Pandas es una biblioteca de código abierto para el lenguaje de programación Python diseñada para el análisis y la manipulación de dato
"""

import pandas as pd

"""##Ejemplo de un Dataframe"""

data= {
    "nombres":["hugo","paco","luis"],
    "sexo":["men,","men","men"],
    "edad":[12,11,13]
}
df = pd.DataFrame(data)
print(df)

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

"""#ahora tenemos la clase de tipos de netflix

df.head() te muestra las tabla sin imoportat la cantidad de datos pero si ponemos por ejemplo
df.head(10) nos mostrara las primeras 10 filas de la tabla
"""

from google.colab import files
uploaded = files.upload()  # te abre un botón para subir el archivo

df = pd.read_csv("netflix_data.csv")

df.head()

df.head(10)

"""#dato importante nos mostrata el 10 dado que en programacion se cuenta es desde el 0 no desde el 1 asi que no mostrara la ultima fila osea el 10

# df.info() te sirve para conocer la estructura interna del DataFrame, algo que .head() no te muestra bien.
"""

df.info()

#   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nombres   4813 non-null   object
 1   sexo      4813 non-null   object
 2   edad      4813 non-null   int64

"""##te dice el tamaño del DataFrame: cuántas filas y columnas tiene. df.shape()"""

df.shape

"""##Te da estadísticas rápidas de las columnas numéricas del DataFrame: promedio, mínimo, máximo, etc.df,describe()"""

df.describe()

"""Fila	Qué es
count	Cuántos valores no nulos hay
mean	El promedio
std	Qué tan dispersos están los datos (desviación estándar)
min	El valor más chico
25%, 50%, 75%	Percentiles (el 50% es la mediana)
max	El valor más grande

#####TAREA
"""

df['genre'].unique()

"""##Selecciona solo la columna genre del DataFrame. Esto te da una lista larga con el género de cada una de las 4813 filas — pero con muchos valores repetidos (porque hay muchas películas de "Dramas", muchas de "Comedies", etc.).

##.unique()

##Toma esa columna y elimina los duplicados, dejándote solo los valores distintos que existen.
"""

df[df['genre'] == 'Cult Movies']

"""#"El == crea una plantilla (máscara) que marca con True/False cuáles géneros son 'Cult Movies'. Luego el df[ ] de afuera usa esa plantilla para colar solo las filas marcadas True de la tabla original."
"""